
title: My Resume
url: 'http://asmita-pandey.github.io'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Asmita Pandey  ## put your name
title: 'Machine Learning &amp; AI Developer for Nanotechnology'  ## your title
location: Beijing, China


## Social Profiles
facebook: https://www.facebook.com/asmi.pandey.7  ## your facebook account url
twitter: https://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
